### ISSUE TITLE
CCOrbitCamera does not rotate about central axis

### ISSUE THREAD

**Issue by dustinanon** [ZhouWeikuan/cocos2d#26]
On my coworker's iPad (using cocos2d-iphone 0.99.4), CCOrbitCamera rotates horizontally about the Y-Axis and rotates vertically about the X-Axis, that is it rotates about the center both ways.

When I use CCOrbitCamera for Android, rotating horizontally always rotates about the left-hand side of the CCNode, and rotating vertically always rotates about the top side of the CCNode.

The code for CCOrbitCamera is a 1:1 translation between cocos2d-android and cocos2d-iphone, so I don't know where this bug is coming from.

As usual, thanks in advance!

**Comment by ZhouWeikuan** [comment]
It might live in cocos2d-android because CCorbigCamera is advanced feature,
it uses grid and the related opengl is not always correctly translated/

2011/7/20 dustinanon <
reply@reply.github.com>

**Comment by dustinanon** [comment]
mmm, I see.  I'm not too familiar with the OpenGL concepts, but I know that the camera values, and the values generated within CCOrbitCamera are exactly the same between android and iOS.

Do you happen to know where I might look for the OpenGL stuff?

**Comment by ZhouWeikuan** [comment]
OpenGL nehe?
I just know this lessons, and also a newbie on OpenGL:-)

2011/7/21 dustinanon <
reply@reply.github.com>

**Comment by dustinanon** [comment]
Scratch all this.  I'm an idiot.  I had the anchor point set to (0,1)

-hangs head-
