### ISSUE TITLE
Screen gets Blank-out on 'onPause' & 'onResume' 

### ISSUE THREAD

**Issue by sourceBreaker** [ZhouWeikuan/cocos2d#28]
In my application when i press home button and after that resume my application my textures do not get redraw.I had called CCDirector.onPause and CCDirector.onResume in my Activity`s onPause and onResume.

Do cocos2d supports this functionality if it does then how ? ? ? 

i have tried this on cocos2d samples as well and they are behaving same .

**Comment by oji** [comment]
I'm having the same issue.
