### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by shahbazsajjad** [ZhouWeikuan/cocos2d#4]
We are facing memory issue in cocos2d android. A class name as GLResourceHelper increases its size dramatically. Whenever we call removealltextures after this when we reload the textures again this GLResourceHelper gain its size to 1 mb + every time. Please fix this issue as soon as possible.

Regards

Shahbaz Sajjad

**Comment by opengenius** [comment]
i've uncommited clean up string in remove textures, now there are shouldn't be any leaks.

**Comment by shahbazsajjad** [comment]
It fixed this issue. But now we are facing issue of VM budget on Bitmap.createBitmap.
Please let us know this issue is regarding cocos or this is a issue of android bitmap.

Regards

Shahbaz Sajjad
