### ISSUE TITLE
Bitmap exceeds VM budget

### ISSUE THREAD

**Issue by b0ktai** [ZhouWeikuan/cocos2d#5]
I had been banging my head to the wall with this error when loading multiple sprites. I solved it by recycling the bitmap after it was used:

bmp.recycle();
bmp = null;
is = null;

The modified function was the following, in CCTextureCache class:

private static CCTexture2D createTextureFromFilePath(final String path) {

```
    final CCTexture2D tex = new CCTexture2D();
    tex.setLoader(new GLResourceHelper.GLResourceLoader() {

        public void load() {
            try {
                InputStream is = CCDirector.sharedDirector().getActivity().getAssets().open(path);
                Bitmap bmp = BitmapFactory.decodeStream(is);
                is.close();
                tex.initWithImage(bmp);
                bmp.recycle();
                bmp = null;
                is = null;
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    });

    return tex;
}
```

Can you confirm this bug, or if there is another workaround I am not aware off.

This error seems to happen because GC doesn´t free memory at the needed rate...

**Comment by ZhouWeikuan** [comment]
yes, it is a bug, and we have to save bmp without recycling it to restore
when the app is back and we have to load everything for it.

Thanks,
Weikuan Zhou

2011/4/12 b0ktai <
reply@reply.github.com>

**Comment by opengenius** [comment]
recycle is called in loadTexture method of CCTexture2D now.

**Comment by b0ktai** [comment]
I may be confusing something here, but I don't understand the load thing. If the load you're mentioning is the onStart() event of the activity, then there is no need to load the layer again. If the activity enters an onStop() state there is no need to call CCDirector.sharedDirector().end(); so when the activity comes back up there's no need to load anything again...

In my understanding I only call CCDirector.sharedDirector().end(); at the onDestroy event and nowhere else...

**Comment by b0ktai** [comment]
Sorry didn't see you're last post.

Thank you.
