### ISSUE TITLE
How to launch the examples of the Android Coco2D project ?

### ISSUE THREAD

**Issue by agGitHub** [ZhouWeikuan/cocos2d#50]
Hi,

I really don't understand what to do with the following instructions :

"How to run the tests
Create a local.properties file with sdk.dir=/path_to_android_sdk
Then, type 'ant install' and enjoy!"

written here: https://github.com/ldesegur/cocos2d-android/blob/master/README

Can you give the step by step approach ? (I am on Mac)

Thanks.

**Comment by ZhouWeikuan** [comment]
Just import cocos2d-android into your eclipse(I'm using eclipse and don't
know ant at all).
Set it is an app instead of library and run it in android machine.

2011/12/14 agGitHub <
reply@reply.github.com

> Hi,
> 
> I really don't understand what to do with the following instructions :
> 
> ## "How to run the tests
> 
> Create a local.properties file with sdk.dir=/path_to_android_sdk
> 
> Then, type 'ant install' and enjoy!"
> 
> written here:
> https://github.com/ldesegur/cocos2d-android/blob/master/README
> 
> Can you give the step by step approach ? (I am on Mac)
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ZhouWeikuan/cocos2d/issues/50

## 

This is Zhou, Weikuan(Ϊ)

**Comment by agGitHub** [comment]
Thanks !!! Yes it works !

2011/12/14 Zhou Weikuan <
reply@reply.github.com

> Just import cocos2d-android into your eclipse(I'm using eclipse and don't
> know ant at all).
> Set it is an app instead of library and run it in android machine.
> 
> 2011/12/14 agGitHub <
> reply@reply.github.com
> 
> > Hi,
> > 
> > I really don't understand what to do with the following instructions :
> > 
> > ## "How to run the tests
> > 
> > Create a local.properties file with sdk.dir=/path_to_android_sdk
> > 
> > Then, type 'ant install' and enjoy!"
> > 
> > written here:
> > https://github.com/ldesegur/cocos2d-android/blob/master/README
> > 
> > Can you give the step by step approach ? (I am on Mac)
> > 
> > Thanks.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ZhouWeikuan/cocos2d/issues/50
> 
> ## 
> 
> This is Zhou, Weikuan(Ϊ)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ZhouWeikuan/cocos2d/issues/50#issuecomment-3134478

## 

Régis ANDRE
http://AudioGuidia.com
Follow us on: Twitter http://twitter.com/audioguidia /
Facebookhttps://www.facebook.com/pages/World-Explorer/187630167934757?v=wall
