### ISSUE TITLE
Android equivalent of Cocos2D-iOS CCNode.visit() in Cocos2D-Android?

### ISSUE THREAD

**Issue by agGitHub** [ZhouWeikuan/cocos2d#52]
Hi,

I have got the following code in my iOS Coco2D game:

CCSprite *mysprite = [CCSprite spriteWithFile:@"mypng.png"];
// ...Some code here... //
[mysprite visit];

In Coco2D Android, I write:

CCSprite mysprite = CCSprite.sprite("mypng.png");
// ...Some code here... //
mysprite.visit(***_GL10 PARAMETER EXPECTED HERE**_**);

What should I write as parameter in the visit method ??

Thanks !!

**Comment by shashachu** [comment]
The director has a static reference to the GL10 object:

CCDirector.gl

**Comment by agGitHub** [comment]
Thanks it works !
