### ISSUE TITLE
Issue when using using landscape mode

### ISSUE THREAD

**Issue by BMR11** [ZhouWeikuan/cocos2d#60]
Hi,
When we use 
CCDirector.sharedDirector().setDeviceOrientation(CCDirector.kCCDeviceOrientationLandscapeLeft) its having issue when we press lock button.
When we press lock button it calls onPause->onStop->onDestroy.. So we are thrown out of out applicaton.
When we are back from locked screen it shows home screen of phone , because onDestroy called.
But when we use CCDirector.kCCDeviceOrientationPortrait its working fine, I mean it wont call onDestroy and we are resumed to same screen when we are back from lock screen.

Please anybody have faced the issue?
Thanks
-BMR

**Comment by opengenius** [comment]
Try adding for your activity instead of setDeviceOrientation.
android:configChanges="orientation|keyboardHidden"
android:screenOrientation="landscape"

**Comment by BMR11** [comment]
Thanks ,
It worked for me.
-BMR.
